version: '3.8'

services:
  # TrueTweet Backend API
  api:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: ./data/database.sqlite
      DATABASE_MEMORY: false
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev-super-secret-jwt-key-change-this-in-production-please
      JWT_EXPIRES_IN: 24h
      JWT_REFRESH_EXPIRES_IN: 7d
      CORS_ORIGIN: http://localhost:3000,http://localhost:5173
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      LOG_LEVEL: debug
      LOG_FORMAT: simple
      CACHE_TTL: 3600
      TIMELINE_CACHE_SIZE: 1000
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - truetweet-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - truetweet-network
    restart: unless-stopped

  # Redis Commander (optional - for Redis management)
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - truetweet-network
    profiles:
      - tools

networks:
  truetweet-network:
    driver: bridge

volumes:
  redis-data:
